apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icinga2.fullname" . }}-master-1
  labels:
    {{ include "icinga2.labels" . | indent 4 | trim }}
    component: icinga2-master-1

# data:

stringData:
  HOSTNAME: {{ .Values.icinga2.master1.hostname | quote }}
  ICINGA2_MASTER: {{ .Values.icinga2.master1.hostname | quote }}
  # ICINGA2_PARENT: {{ .Values.icinga2.master1.parent | quote }}
  ICINGA2_API_USERS:        "{{ .Values.icinga2.auth.cmdApiUser     }}:{{ .Values.icinga2.auth.cmdApiPass     }}"
  ICINGA2_API_PROM_USER:    "{{ .Values.icinga2.auth.apiPromUser    }}:{{ .Values.icinga2.auth.apiPromPass    }}"
  ICINGA2_API_HACHECK_USER: "{{ .Values.icinga2.auth.apiHACheckUser }}:{{ .Values.icinga2.auth.apiHACheckPass }}"
  TICKET_SALT: "{{ .Values.icinga2.master.ticketSalt }}"
  AGENT_HEALTH_CHECK_SEC: "60s"
  AGENT_HEALTH_RETRY_SEC: "60s"
  PAGERDUTY:          "{{ .Values.icinga2.PagerDuty }}"

  # HA-Part
  {{ if not .Values.icinga2.master2.disable }}
  MULTI_MASTER:     "true"
  HA_CONFIG_MASTER: "true"
  {{ else }}
  MULTI_MASTER:     "false"
  {{ end }}
  HA_MASTER1:       {{ .Values.icinga2.master1.hostname | quote }}
  {{ if not .Values.icinga2.master2.disable }}
  HA_MASTER2:       {{ .Values.icinga2.master2.hostname | quote }}
  HA_MASTER2_PORT:  "5665"
  {{ end }}

  # service name config
  K8S_USE_SVC:        "true"
  HA_MASTER1_SVCNAME: "{{ include "icinga2.fullname" . }}-master-1"
  {{ if not .Values.icinga2.master2.disable }}
  HA_MASTER2_SVCNAME: "{{ include "icinga2.fullname" . }}-master-2"
  {{ end }}
  K8S_NAMESPACE:      "{{ .Release.Namespace }}"
  K8S_DOMAIN:         "svc.{{ default "cluster.local" .Values.clusterDomain }}"

  # MySQL
  MYSQL_HOST:      {{ .Values.icinga2.mysql.host     | quote }}
  MYSQL_PORT:      {{ .Values.icinga2.mysql.port     | quote }}
  MYSQL_ROOT_USER: {{ .Values.icinga2.mysql.rootUser | quote }}
  MYSQL_ROOT_PASS: {{ .Values.icinga2.mysql.rootPass | quote }}

  IDO_USER:          "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  IDO_DATABASE_NAME: "{{ .Values.icinga2.mysql.ic2DbPrefix }}ido"
  IDO_PASSWORD:       {{ .Values.icinga2.mysql.ic2UserPass | quote }}
  ICINGADB:          "{{ .Values.icinga2.IcingaDB }}"

  # IcingaDB-Part
  {{ if .Values.icinga2.IcingaDB -}}
  ICINGADB_USER:     "{{ .Values.icinga2.mysql.ic2UserPrefix }}icinga"
  ICINGADB_DATABASE_NAME: "{{ .Values.icinga2.mysql.ic2UserPrefix }}icingadb"
  ICINGADB_PASSWORD:  {{ .Values.icinga2.mysql.ic2UserPass | quote }}
  {{- end }}

  ICINGA2_MSMTP_RELAY_SERVER:       "{{ .Values.icinga2.msmtp.relayServer }}"
  ICINGA2_MSMTP_REWRITE_DOMAIN:     "{{ .Values.icinga2.msmtp.rewriteDomain }}"
  ICINGA2_MSMTP_RELAY_USE_STARTTLS: "{{ .Values.icinga2.msmtp.relayUseStartTLS }}"
  ICINGA2_MSMTP_SENDER_EMAIL:       "{{ .Values.icinga2.msmtp.senderEmail }}"
  ICINGA2_MSMTP_SMTPAUTH_USER:      "{{ .Values.icinga2.msmtp.smtpAuthUser }}"
  ICINGA2_MSMTP_SMTPAUTH_PASS:      "{{ .Values.icinga2.msmtp.smtpAuthPass }}"
  ICINGA2_MSMTP_RECV_ROOT:          "{{ .Values.icinga2.msmtp.recvRoot }}"
  ICINGA2_MSMTP_ACC_NAME:           "{{ .Values.icinga2.msmtp.accName }}"

{{ if and (eq .Values.icinga2.influxdb.enable true) (eq .Values.icinga2.influxdb.version "v1") }}
  INFLUXDB_HOST: {{ include "icinga2.fullname" . }}-influxdb
  INFLUXDB_PORT: {{ .Values.icinga2.influxdb.port | quote }}
  INFLUXDB_DB:   {{ .Values.icinga2.influxdb.db   | quote }}
  INFLUXDB_USER: {{ .Values.icinga2.influxdb.user | quote }}
  INFLUXDB_PASS: {{ .Values.icinga2.influxdb.pass | quote }}
{{ end }}

{{ if and (eq .Values.icinga2.influxdb.enable true) (eq .Values.icinga2.influxdb.version "v2") }}
  INFLUXDB_HOST: {{ include "icinga2.fullname" . }}-influxdb
  INFLUXDB_PORT: {{ .Values.icinga2.influxdb.port | quote }}
  INFLUXDB_BUCKET: {{ .Values.icinga2.influxdb.bucket | quote }}
  INFLUXDB_ORGANIZATION: {{ .Values.icinga2.influxdb.organization | quote }}
  INFLUXDB_TOKEN: {{ .Values.icinga2.influxdb.token | quote }}
{{ end }}

{{ if .Values.icinga2.graphite.enable }}
  CARBON_HOST: {{ .Values.icinga2.graphite.host | quote }}
  CARBON_PORT: {{ .Values.icinga2.graphite.port | quote }}
  CARBON_TRESHOLDS: "true"
  CARBON_METADATA: "true"
{{ end }}

  DEBUG: "0"
  LOG_LEVEL: "warning"
  # S6
  S6_CMD_WAIT_FOR_SERVICES_MAXTIME: {{ .Values.icinga2.master.s6_timeout | quote }}
